import type { SkillDefinition } from './types'

export const chatSkill: SkillDefinition = {
  id: 'chat',
  name: 'Chat',
  description: 'Handles quick conversation, simple answers, summaries, and everyday help through Nebula.',
  enabled: true,
  requiredPermissions: [],
  riskLevel: 'safe',
  category: 'chat',
  version: '0.2.0',
  keywords: ['chat', 'hello', 'summary', 'explain', 'question', 'conversation'],
  requiredTools: [],
  modelPreference: 'daily',
  canRunInParallel: true,
  supportsVoice: true,
  supportsBackgroundExecution: false,
  estimatedLatencyMs: 700,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Chat skill: keep simple replies concise and useful.'],
  examples: ['Summarize this in one paragraph.', 'Explain what this error means.'],
}

export const codingSkill: SkillDefinition = {
  id: 'coding',
  name: 'Coding',
  description: 'Plans and performs programming, debugging, refactoring, UI work, and integration tasks.',
  enabled: true,
  requiredPermissions: ['files.read'],
  riskLevel: 'needs_approval',
  category: 'coding',
  version: '0.2.0',
  keywords: ['code', 'coding', 'debug', 'fix', 'refactor', 'typescript', 'react', 'tauri', 'build'],
  requiredTools: ['read_file', 'list_files'],
  modelPreference: 'code',
  canRunInParallel: false,
  supportsVoice: false,
  supportsBackgroundExecution: true,
  estimatedLatencyMs: 3500,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Coding skill: read before editing, keep changes scoped, and verify with tests/builds when available.'],
  examples: ['Fix this TypeScript error.', 'Implement a focused UI change.'],
}

export const reviewSkill: SkillDefinition = {
  id: 'review',
  name: 'Review',
  description: 'Provides senior review for correctness, safety, architecture, performance, and maintainability.',
  enabled: true,
  requiredPermissions: ['files.read'],
  riskLevel: 'safe',
  category: 'review',
  version: '0.2.0',
  keywords: ['review', 'audit', 'check', 'safe', 'security', 'performance', 'architecture', 'bugs'],
  requiredTools: ['read_file'],
  modelPreference: 'review',
  canRunInParallel: true,
  supportsVoice: false,
  supportsBackgroundExecution: true,
  estimatedLatencyMs: 6000,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Review skill: lead with concrete findings, severity, and recommended fixes.'],
  examples: ['Review this plan for risks.', 'Find bugs in this implementation.'],
}

export const diagnosticsSkill: SkillDefinition = {
  id: 'diagnostics',
  name: 'Diagnostics',
  description: 'Tracks model routing, latency, memory usage, skill health, and runtime decisions.',
  enabled: true,
  requiredPermissions: ['system.read'],
  riskLevel: 'safe',
  category: 'diagnostics',
  version: '0.2.0',
  keywords: ['diagnostics', 'latency', 'model', 'route', 'vram', 'ram', 'health', 'stats'],
  requiredTools: ['get_system_info'],
  modelPreference: 'review',
  canRunInParallel: true,
  supportsVoice: false,
  supportsBackgroundExecution: true,
  estimatedLatencyMs: 600,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Diagnostics skill: expose internal state only when debug mode or diagnostics views are being used.'],
  examples: ['Why was this model selected?', 'Show skill health.'],
}

export const voiceSkill: SkillDefinition = {
  id: 'voice',
  name: 'Voice',
  description: 'Routes voice overlay input through the same Nebula chat/task pipeline.',
  enabled: true,
  requiredPermissions: ['microphone.use'],
  riskLevel: 'needs_approval',
  category: 'voice',
  version: '0.2.0',
  keywords: ['voice', 'microphone', 'talk', 'speak', 'transcript', 'overlay'],
  requiredTools: [],
  modelPreference: 'daily',
  canRunInParallel: true,
  supportsVoice: true,
  supportsBackgroundExecution: true,
  estimatedLatencyMs: 900,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Voice skill: keep spoken responses short and conversational unless the user asks for detail.'],
  examples: ['Answer this through voice mode.', 'Use the transcript as the user request.'],
}

export const clipboardSkill: SkillDefinition = {
  id: 'clipboard',
  name: 'Clipboard',
  description: 'Future local clipboard integration placeholder. Metadata only until clipboard tools are implemented.',
  enabled: false,
  requiredPermissions: ['clipboard.read', 'clipboard.write'],
  riskLevel: 'needs_approval',
  category: 'clipboard',
  version: '0.1.0',
  keywords: ['clipboard', 'copy', 'paste'],
  requiredTools: ['clipboard_read', 'clipboard_write'],
  modelPreference: 'auto',
  canRunInParallel: true,
  supportsVoice: true,
  supportsBackgroundExecution: false,
  estimatedLatencyMs: 500,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Clipboard skill is metadata-only until local clipboard tools are added.'],
  examples: ['Read the clipboard.', 'Copy this answer.'],
}

export const emailSkill: SkillDefinition = {
  id: 'email',
  name: 'Email',
  description: 'Future email connector placeholder. Metadata only until a local/connector executor is configured.',
  enabled: false,
  requiredPermissions: ['email.send', 'internet.use'],
  riskLevel: 'high_risk',
  category: 'email',
  version: '0.1.0',
  keywords: ['email', 'send', 'gmail', 'message'],
  requiredTools: ['email_send'],
  modelPreference: 'auto',
  canRunInParallel: false,
  supportsVoice: true,
  supportsBackgroundExecution: true,
  estimatedLatencyMs: 2500,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Email skill is metadata-only until an email connector is configured. Never claim an email was sent without a tool result.'],
  examples: ['Summarize my README and send it by email.'],
}

export const minecraftBotSkill: SkillDefinition = {
  id: 'minecraft-bot',
  name: 'Minecraft Bot',
  description: 'Future game automation integration placeholder. Metadata only until a safe local bot bridge exists.',
  enabled: false,
  requiredPermissions: ['apps.launch'],
  riskLevel: 'needs_approval',
  category: 'game',
  version: '0.1.0',
  keywords: ['minecraft', 'bot', 'game', 'server'],
  requiredTools: ['minecraft_bot'],
  modelPreference: 'code',
  canRunInParallel: false,
  supportsVoice: true,
  supportsBackgroundExecution: true,
  estimatedLatencyMs: 5000,
  estimatedCost: 'free',
  tools: [],
  systemPromptAdditions: ['Minecraft Bot skill is metadata-only until a safe local bot executor is implemented.'],
  examples: ['Have the Minecraft bot gather wood.'],
}

export const coreAgentSkills = [
  chatSkill,
  codingSkill,
  reviewSkill,
  diagnosticsSkill,
  voiceSkill,
  clipboardSkill,
  emailSkill,
  minecraftBotSkill,
]
